engines:
  apexmetrics:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
      - .resource
  csslint:
    enabled: true
ratings:
  paths:
    - "**.cls"
    - "**.trigger"
    - "**_js.resource"
    - "**_jstest.resource"
    - "**_css.resource"
exclude_paths:
  - "src/documents/"
  - "src/classes/MetadataService.cls"
  - "src/classes/MetadataServiceTest.cls"
  - "src/classes/SObjectDataLoader.cls"
  - "src/classes/SObjectDataLoader_Test.cls"
  - "src/classes/SmartFactory.cls"
  - "src/classes/fflib_IDGenerator.cls"
  - "src/classes/fflib_IDGeneratorTest.cls"
  - "src/classes/fflib_ISObjectDomain.cls"
  - "src/classes/fflib_ISObjectSelector.cls"
  - "src/classes/fflib_ISObjectUnitOfWork.cls"
  - "src/classes/fflib_QueryFactory.cls"
  - "src/classes/fflib_QueryFactoryTest.cls"
  - "src/classes/fflib_SObjectDescribe.cls"
  - "src/classes/fflib_SObjectDescribeTest.cls"
  - "src/classes/fflib_SObjectDomain.cls"
  - "src/classes/fflib_SObjectDomainTest.cls"
  - "src/classes/fflib_SObjectSelector.cls"
  - "src/classes/fflib_SObjectSelectorTest.cls"
  - "src/classes/fflib_SObjectUnitOfWork.cls"
  - "src/classes/fflib_SObjectUnitOfWorkTest.cls"
  - "src/classes/fflib_SecurityUtils.cls"
  - "src/classes/fflib_SecurityUtilsTest.cls"
  - "src/classes/fflib_StringBuilder.cls"
  - "src/classes/fflib_StringBuilderTest.cls"
  - "src/classes/ToolingAPI.cls"
  - "src/classes/ToolingAPITest.cls"
  - "**.schema"
  - "**.xml"
  - "**.actionLinkGroupTemplate"  
  - "**.snapshot" 
  - "**.component"
  - "**.page" 
  - "**.appMenu"
  - "**.approvalProcess"  
  - "**.assignmentRules"
  - "**.authprovider" 
  - "**.autoResponseRules"
  - "**.callCenter" 
  - "**.crt"
  - "**.channelLayout"  
  - "**.community"
  - "**.connectedApp" 
  - "**.corsWhitelistOrigin"
  - "**.app"  
  - "**.customApplicationComponent"
  - "**.feedFilter" 
  - "**.labels"
  - "**.md" 
  - "**.object"
  - "**.objectTranslation"  
  - "**.weblink"
  - "**.customPermission" 
  - "**.site"
  - "**.tab"  
  - "**.dashboard"
  - "**.datacategorygroup"  
  - "**.delegateGroup"
  - "**.email"  
  - "**.escalationRules"
  - "**.dataSource" 
  - "**.flexipage"
  - "**.flow" 
  - "**.flowDefinition"
  - "**.group"  
  - "**.homePageComponent"
  - "**.homePageLayout" 
  - "**.installedPackage"
  - "**.layout" 
  - "**.letter"
  - "**.matchingRule" 
  - "**.namedCredential"
  - "**.pathAssistant"  
  - "**.permissionset"
  - "**.cachePartition" 
  - "**.portal"
  - "**.postTemplate" 
  - "**.profile"
  - "**.queue"  
  - "**.quickAction"
  - "**.remoteSite" 
  - "**.report"
  - "**.reportType" 
  - "**.role"
  - "**.samlssoconfig"  
  - "**.scf"
  - "**.settings" 
  - "**.sharingRules"
  - "**.sharingSet"
  - "**.site" 
  - "**.resource"
  - "**.synonymDictionary"
  - "**.transactionSecurityPolicy"  
  - "**.workflow"
  - "**.xorghub"
  - "**.globalPicklist"
  - "**.translation"
